# Generated by Django 6.1.1 on 2026-09-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor_str', models.CharField(max_length=100)),
                ('anio', models.IntegerField(verbose_name='Año de publicación')),
            ],
        ),
    ]
