# Generated by Django 6.1.1 on 2026-10-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoReserva',
            new_name='Producto_reserva',
        ),
    ]
